server:
  port: 8081

spring:
  application:
    name: marsreg-document
  datasource:
    url: jdbc:mysql://rm-bp122j6l43ik18389bo.mysql.rds.aliyuncs.com:3306/mars_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: marsdb_2025
    password: Mars2025
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # 连接池最大连接数
      maximum-pool-size: 20
      # 最小空闲连接数
      minimum-idle: 5
      # 连接超时时间（毫秒）
      connection-timeout: 30000
      # 空闲连接超时时间（毫秒）
      idle-timeout: 600000
      # 连接最大生命周期（毫秒）
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        # 批量插入大小
        jdbc.batch_size: 50
        # 批量更新大小
        order_inserts: true
        order_updates: true
        # 二级缓存配置
        cache:
          use_second_level_cache: false
          use_query_cache: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  cache:
    type: simple
    cache-names: documentChunks,documentContent
    simple:
      # 缓存过期时间（毫秒）
      time-to-live: 3600000
      # 缓存最大大小
      max-size: 1000
  task:
    execution:
      pool:
        core-size: 4
        max-size: 8
        queue-capacity: 100
        keep-alive: 60s
  main:
    allow-bean-definition-overriding: true
  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 1s
    socket-timeout: 30s
    username: elastic
    password: changeme
  data:
    elasticsearch:
      repositories:
        enabled: true
      client:
        reactive:
          endpoints: localhost:9200
          username: elastic
          password: changeme

logging:
  level:
    com.marsreg: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

marsreg:
  document:
    chunking:
      # 默认最大块大小（字符数）
      default-max-chunk-size: 1000
      # 默认最小块大小（字符数）
      default-min-chunk-size: 200
      # 默认重叠大小（字符数）
      default-overlap-size: 100
      # 是否启用智能分块
      enable-smart-chunking: true
      # 是否在句子边界分割
      split-on-sentence-boundary: true
      # 是否在段落边界分割
      split-on-paragraph-boundary: true
      # 是否保持段落完整性
      preserve-paragraph-integrity: true
    index:
      # 是否启用索引
      enabled: true
      # 索引刷新间隔（毫秒）
      refresh-interval: 300000
      # 索引批处理大小
      batch-size: 100
      # 是否异步索引
      async: true
      # 索引线程池大小
      thread-pool-size: 4
    rate-limit:
      # 默认限流配置
      default:
        limit: 10
        time-window: 60  # 秒
      # 文件上传限流配置
      upload:
        limit: 5
        time-window: 60  # 秒
      # 文件下载限流配置
      download:
        limit: 20
        time-window: 60  # 秒
    alert:
      failure-rate-threshold: 0.1
      slow-upload-threshold: 5000
    upload:
      part-size: 5242880  # 5MB
      temp-dir: ${java.io.tmpdir}/marsreg-uploads
      max-retries: 3
      retry-delay: 1000
      compression:
        enabled: true
        quality: 0.8
        max-width: 1920
        max-height: 1080

aliyun:
  oss:
    endpoint: ${OSS_ENDPOINT:oss-cn-hangzhou.aliyuncs.com}
    accessKeyId: ${OSS_ACCESS_KEY_ID}
    accessKeySecret: ${OSS_ACCESS_KEY_SECRET}
    bucketName: ${OSS_BUCKET_NAME}
    urlExpiration: ${OSS_URL_EXPIRATION:3600}
    maxFileSize: ${OSS_MAX_FILE_SIZE:10485760}  # 默认10MB
    allowedFileTypes: ${OSS_ALLOWED_FILE_TYPES:jpg,jpeg,png,gif,pdf,doc,docx,xls,xlsx,txt} 