spring:
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  datasource:
    url: jdbc:mysql://localhost:3306/marsreg?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: marsreg

marsreg:
  backup:
    backup-dir: /data/marsreg/backups
    mysql-bin-path: /usr/bin/mysql
    mysql-username: root
    mysql-password: root
    mysql-database: marsreg
    retention-days: 7
    auto-backup: true
    cron-expression: "0 0 2 * * ?"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
  packages-to-scan: com.marsreg
  paths-to-match: /api/**

# jwt:
#   secret: your-secret-key-here-must-be-at-least-32-characters-long
#   expiration: 86400000 # 24 hours in milliseconds

logging:
  level:
    com.marsreg: INFO
    org.springframework.security: INFO 