server:
  port: 8082

spring:
  application:
    name: marsreg-vector
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 10000
      lettuce:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0

marsreg:
  vector:
    # 模型配置
    model:
      name: sentence-transformers/all-MiniLM-L6-v2
      version: 1.0.0
      dimension: 384
      path: https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2
      device: cpu  # cpu 或 gpu
      batch-size: 32
    # 线程池配置
    thread-pool-size: 4
    # 缓存配置
    cache:
      enabled: true
      expire: 3600
    # Milvus配置
    milvus:
      host: localhost
      port: 19530
      collection: marsreg_vectors
      dimension: 384
      # 认证配置
      auth:
        enabled: true
        token: "your-token"
      # 索引配置
      index:
        type: IVF_SQ8
        nlist: 1024
        metric-type: COSINE

logging:
  level:
    com.marsreg.vector: INFO
    ai.djl: INFO 